server:
  port: 9090

my:
  hello: Hello my friend

spring:
  profiles:
    active: default

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
